### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by gakimball** [zurb/panini#7]
Here's what this thing needs before Foundation 6 comes out:

- [x] Pre-configure settings (#6) e8a8b878edb91b2441a6881a6f7b1215234f2a6b
- [x] Configure using directories, not globs e8a8b878edb91b2441a6881a6f7b1215234f2a6b
- [x] Split `index.js` into functional areas e8a8b878edb91b2441a6881a6f7b1215234f2a6b ac9cf8ce6b77a76320a0afce1fb40350b4bb4d0b
- [x] Handlebars variables/helpers
  - [x] `root`: prepends a relative path to a URL 00f24b5c5f1ed6a31a2f9ae25e699d9fb76490f8
  - [x] `#pageis`/`#pageisnt`: prints content based on name of page ecd75b102f60eb270862bc659eb32916398b417e
  - [x] `#repeat`: repeats content `n` number of times c76926c4b99f8f043f66dacea995544f5f8b8059
  - [ ] ~~Add [assemble/handlebars-helpers](https://github.com/assemble/handlebars-helpers)~~

**Comment by lyckron** [comment]
If you make a `develop` branch with a basic skeleton of what you have in mind,  I'll be happy to pitch in.

**Comment by Abhra1992** [comment]
I believe panini should have the option for configuration using both directories and globs.

Adding `assemble/handlebars-helpers` is an excellent idea, but it might lead to problems in templates. Sometimes the helpers don't register correctly as that library targets HBS v1.0.3^ and not v4.0.0^

**Comment by gakimball** [comment]
@lyckron That would be fantastic! I plan on grinding out a lot of this stuff out this weekend. I could use support on the test suite, because realistically I can't devote too much time to it in the short term, due to time constraints.

**Comment by gakimball** [comment]
1.0 is OUT OUT OUT

**Comment by alexeych** [comment]
Hello there,
is there any way to use `assemble/handlebars-helpers` with the current version of Panini?
